# Copyright (c) 2022-2025, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

seed: 42


# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: True

  # vel_encoder:
  #   class: Encoder
  #   network_type: mlp
  #   input_key: policy
  #   output_key: vel_est
  #   # latent_dim: 64
  #   hidden_dims: [256, 128]
  #   activation: elu
  #   # input_mode only affects Runner's space selection:
  #   # - obs_only (default): uses observation_space
  #   # - state_only: uses state_space  
  #   # For recurrent networks, use:
  #   # network_type: recurrent
  #   # recurrent_type: lstm  # or gru
  #   # num_layers: 1
  #   # hidden_size: 256

  policy:  # see gaussian_model parameters
    class: SimpleGaussian
    init_noise_std: 1.0
    actor_hidden_dims: [512, 256, 128]
    activation: elu
    noise_std_type: "log"
    input_key: policy # + vel_est
    share_std_backbone: False
    use_scale_tril: False  # must use share_std_backbone?
    output_action_scale: False
    max_log_std: 2.0
    min_log_std: -20.0
    max_action: 100.0
    min_action: -100.0
    noise_generator: None
    noise_generator_kwargs: 
      theta: 0.5  # control the decay speed of the noise: tune 0.5 ~ 0.7
      sigma: 0.7  # control the amplitude of the noise: tune 0.7 ~ 1.0
      base_scale: 1.0  # use default 1.0
      mean: 0.0  # use default 0.0
      std: 1.0  # use default 1.0

  value:  # see deterministic_model parameters
    class: SimpleDeterministic
    hidden_dims: [512, 256, 128]
    activation: elu


# Rollout memory
# https://skrl.readthedocs.io/en/latest/api/memories/random.html
memory:
  class: Memory
  memory_size: -1  # automatically determined (same as agent:rollouts)


# PPO agent configuration (field names are from PPO_DEFAULT_CONFIG)
# https://skrl.readthedocs.io/en/latest/api/agents/ppo.html
agent:
  class: POMDP_PPO
  rollouts: 24
  learning_epochs: 5
  mini_batches: 4
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 1.0e-03
  learning_rate_scheduler: KLAdaptiveLR
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.01
    min_lr: 1.0e-05
    max_lr: 1.0e-02
    kl_factor: 2.0
    lr_factor: 1.5
  use_encoder: False
  encoder_kwargs:
    model_name: vel_encoder
    obs_name: vel_est
    learning_rate: 1.0e-03
    encoder_preprocessor: RunningStandardScaler
    encoder_preprocessor_kwargs: null
    # encoder_type: concat
  state_preprocessor: RunningStandardScaler
  state_preprocessor_kwargs: null
  actor_observation_preprocessor: RunningStandardScaler
  actor_observation_preprocessor_kwargs: null
  value_preprocessor: RunningStandardScaler
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: True
  entropy_loss_scale: 0.005
  entropy_scheduler: ConstantScheduler
  entropy_scheduler_kwargs:
    decay_factor: 0.99
    decay_interval: 1000
    min_value: 0.003
  grad_penalty_weight: 0.0
  value_loss_scale: 1.0
  kl_threshold: 0.1
  rewards_shaper_scale: 1.0
  time_limit_bootstrap: True
  # logging and checkpoint
  experiment:
    directory: "limx_d03_flat"
    experiment_name: ""
    write_interval: auto
    checkpoint_interval: auto


# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: IsaaclabTrainer
  timesteps: 240000
  environment_info: log
